Organizations:
  - &Pi5
    Name: Pi5
    ID: Pi5MSP
    MSPDir: ../../setup1/Pi5/crypto-config/ordererOrganizations/pi5/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Pi5MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Pi5MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Pi5MSP.admin')"

  - &Laptop1
    Name: Laptop1MSP
    ID: Laptop1MSP

    MSPDir: ../../setup1/Laptop1/crypto-config/peerOrganizations/laptop1/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Laptop1MSP.admin', 'Laptop1MSP.peer', 'Laptop1MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('Laptop1MSP.admin', 'Laptop1MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('Laptop1MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Laptop1MSP.peer')"

    AnchorPeers:
      - Host: endorser1_laptop1
        Port: 7051

  - &Laptop2
    Name: Laptop2MSP

    ID: Laptop2MSP

    MSPDir: ../../setup1/Laptop2/crypto-config/peerOrganizations/laptop2/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Laptop2MSP.admin', 'Laptop2MSP.peer', 'Laptop2MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('Laptop2MSP.admin', 'Laptop2MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('Laptop2MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Laptop2MSP.peer')"

    AnchorPeers:
      - Host: endorser1_laptop2
        Port: 9051

  - &Pi4
    Name: Pi4MSP

    ID: Pi4MSP

    MSPDir: ../../setup1/Pi4/crypto-config/peerOrganizations/pi4/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Pi4MSP.admin', 'Pi4MSP.peer', 'Pi4MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('Pi4MSP.admin', 'Pi4MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('Pi4MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Pi4MSP.peer')"

    AnchorPeers:
      - Host: endorser1_pi4
        Port: 11051

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true

  Orderer: &OrdererCapabilities
    V2_0: true

  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations:

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"

  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft

  EtcdRaft:
    Consenters:
      - Host: orderer1.pi5
        Port: 7050
        ClientTLSCert: ../../setup1/Pi5/crypto-config/ordererOrganizations/pi5/orderers/orderer1.pi5/tls/server.crt
        ServerTLSCert: ../../setup1/Pi5/crypto-config/ordererOrganizations/pi5/orderers/orderer1.pi5/tls/server.crt
  Addresses:
    - orderer1.pi5:7050

  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB

  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  BasicChannel:
    Consortium: SampleConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Laptop1
        - *Laptop2
        - *Pi4
        - *Pi5
      Capabilities:
        <<: *ApplicationCapabilities

  OrdererGenesis:
    <<: *ChannelDefaults
    Capabilities:
      <<: *ChannelCapabilities
    Orderer:
      <<: *OrdererDefaults
      OrdererType: etcdraft
      EtcdRaft:
        Consenters:
          - Host: orderer1.pi5
            Port: 7050
            ClientTLSCert: ../../setup1/Pi5/crypto-config/ordererOrganizations/pi5/orderers/orderer1.pi5/tls/server.crt
            ServerTLSCert: ../../setup1/Pi5/crypto-config/ordererOrganizations/pi5/orderers/orderer1.pi5/tls/server.crt
          - Host: orderer2.pi5
            Port: 8050
            ClientTLSCert: ../../setup1/Pi5/crypto-config/ordererOrganizations/pi5/orderers/orderer2.pi5/tls/server.crt
            ServerTLSCert: ../../setup1/Pi5/crypto-config/ordererOrganizations/pi5/orderers/orderer2.pi5/tls/server.crt
          - Host: orderer3.pi5
            Port: 9050
            ClientTLSCert: ../../setup1/Pi5/crypto-config/ordererOrganizations/pi5/orderers/orderer3.pi5/tls/server.crt
            ServerTLSCert: ../../setup1/Pi5/crypto-config/ordererOrganizations/pi5/orderers/orderer3.pi5/tls/server.crt
      Addresses:
        - orderer1.pi5:7050
        - orderer2.pi5:8050
        - orderer3.pi5:9050

      Organizations:
        - *Pi5
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      SampleConsortium:
        Organizations:
          - *Laptop1
          - *Laptop2
          - *Pi4
