version: "2.4"

networks:
  mainchannel:

services:
  couchdb.endorser1.laptop1:
    container_name: couchdb.endorser1.laptop1
    image: hyperledger/fabric-couchdb:latest
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - mainchannel

  couchdb.endorser2.laptop1:
    container_name: couchdb.endorser2.laptop1
    image: hyperledger/fabric-couchdb:latest
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 6984:5984
    networks:
      - mainchannel

  endorser1.laptop1:
    container_name: endorser1.laptop1
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Laptop1MSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=iot-cc-net

      - CORE_PEER_ID=endorser1.laptop1
      - CORE_PEER_ADDRESS=endorser1.laptop1:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=endorser1.laptop1:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      # Peer used to bootstrap gossip within organisation
      - CORE_PEER_GOSSIP_BOOTSTRAP=endorser1.laptop1:8051
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=endorser1.laptop1:7051

      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.endorser1.laptop1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    depends_on:
      - couchdb.endorser1.laptop1
    ports:
      - 7051:7051
    volumes:
      - ./crypto-config/peerOrganizations/laptop1/peers/endorser1.laptop1/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/laptop1/peers/endorser1.laptop1/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - mainchannel

  endorser2.laptop1:
    container_name: endorser2.laptop1
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=debug
      - CORE_PEER_LOCALMSPID=Laptop1MSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=iot-cc-net

      - CORE_PEER_ID=endorser2.laptop1
      - CORE_PEER_ADDRESS=endorser2.laptop1:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=endorser2.laptop1:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      # Peer used to bootstrap gossip within organisation
      - CORE_PEER_GOSSIP_BOOTSTRAP=endorser2.laptop1:8051
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=endorser1.laptop1:7051

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.endorser2.laptop1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    depends_on:
      - couchdb.endorser2.laptop1
    ports:
      - 8051:8051
    volumes:
      - ./crypto-config/peerOrganizations/laptop1/peers/endorser2.laptop1/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/laptop1/peers/endorser2.laptop1/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - mainchannel

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=endorser1.laptop1:7051
      - CORE_PEER_LOCALMSPID=Laptop1MSP
      # - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/channel/crypto-config/Org1MSP

      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/channel/crypto-config/peerOrganizations/laptop1/peers/endorser1.laptop1/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/channel/crypto-config/peerOrganizations/laptop1/peers/endorser1.laptop1/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/channel/crypto-config/peerOrganizations/laptop1/peers/endorser1.laptop1/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/channel/crypto-config/peerOrganizations/olaptop1/users/Admin@laptop1/msp

      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    networks:
      - mainchannel
    volumes:
      - /var/run/:/host/var/run/
      # - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./crypto-config/peerOrganizations/laptop1/:/etc/hyperledger/channel/crypto-config/peerOrganizations/laptop1/
      - ./../Laptop 2/crypto-config/peerOrganizations/laptop2/:/etc/hyperledger/channel/crypto-config/peerOrganizations/laptop2/
      - ./../Pi 4/crypto-config/peerOrganizations/pi4/:/etc/hyperledger/channel/crypto-config/peerOrganizations/pi4/
      - ./../Pi 5/crypto-config/ordererOrganizations/pi5/:/etc/hyperledger/channel/crypto-config/ordererOrganizations/pi5/
