version: "2.4"

networks:
  mainchannel:

services:
  couchdb.endorser1.laptop2:
    container_name: couchdb.endorser1.laptop2
    image: hyperledger/fabric-couchdb:latest
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 7984:5984
    networks:
      - mainchannel

  couchdb.endorser2.laptop2:
    container_name: couchdb.endorser2.laptop2
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 8984:5984
    networks:
      - mainchannel

  endorser1.laptop2:
    container_name: endorser1.laptop2
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=debug
      - CORE_PEER_LOCALMSPID=Laptop2MSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=iot-cc-net

      - CORE_PEER_ID=endorser1.laptop2
      - CORE_PEER_ADDRESS=endorser1.laptop2:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=endorser1.laptop2:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=endorser1.laptop2:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=endorser2.laptop2:10051

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.endorser1.laptop2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    ports:
      - 9051:9051
    volumes:
      - ./crypto-config/peerOrganizations/laptop2/peers/endorser1.laptop2/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/laptop2/peers/endorser1.laptop2/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - mainchannel

  endorser2.laptop2:
    container_name: endorser2.laptop2
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=debug
      - CORE_PEER_LOCALMSPID=Laptop2MSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=iot-cc-net

      - CORE_PEER_ID=endorser2.laptop2
      - CORE_PEER_ADDRESS=endorser2.laptop2:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=endorser2.laptop2:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=endorser1.laptop2:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=endorser1.laptop2:9051

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.endorser2.laptop2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    ports:
      - 10051:10051
    volumes:
      - ./crypto-config/peerOrganizations/laptop2/peers/endorser2.laptop2/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/laptop2/peers/endorser2.laptop2/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - mainchannel
