version: "2.4"

networks:
  mainchannel:

services:
  couchdb.endorser1.pi4:
    container_name: couchdb.endorser1.pi4
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 9984:5984
    networks:
      - mainchannel

  couchdb.endorser2.pi4:
    container_name: couchdb.endorser2.pi4
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 10984:5984
    networks:
      - mainchannel

  endorser1.pi4:
    container_name: endorser1.pi4
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Pi4MSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=iot-cc-net

      - CORE_PEER_ID=endorser1.pi4
      - CORE_PEER_ADDRESS=endorser1.pi4:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      # - CORE_PEER_CHAINCODEADDRESS=endorser1.pi4:7052
      # - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      # Peer used to bootstrap gossip within organisation
      - CORE_PEER_GOSSIP_BOOTSTRAP=endorser2.pi4:12051
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=endorser1.pi4:11051

      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.endorser1.pi4:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    depends_on:
      - couchdb.endorser1.pi4
    ports:
      - 11051:11051
    volumes:
      - ./crypto-config/peerOrganizations/pi4/peers/endorser1.pi4/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/pi4/peers/endorser1.pi4/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - mainchannel

  endorser2.pi4:
    container_name: endorser2.pi4
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=debug
      - CORE_PEER_LOCALMSPID=Pi4MSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=iot-cc-net

      - CORE_PEER_ID=endorser2.pi4
      - CORE_PEER_ADDRESS=endorser2.pi4:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      # - CORE_PEER_CHAINCODEADDRESS=peer1.org1.example.com:8052
      # - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=endorser2.pi4:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=endorser1.pi4:12051

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.endorser2.pi4:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    ports:
      - 12051:12051
    volumes:
      - ./crypto-config/peerOrganizations/pi4/peers/endorser2.pi4/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/pi4/peers/endorser2.pi4/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - mainchannel
